#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,SC2076,SC2154

source /scripts/common

if ! chk_enabled "$MLAT"; then
    stop_service
fi

echo "Starting sltunnel"
exec "${s6wrap[@]}" /opt/slclient 127.0.0.1:3333 mlat.feed.sdrmap.org:3334 sdrmap.org
